#:schema node_modules/wrangler/config-schema.json
name = "remix-sandbox"
compatibility_date = "2024-10-18"
main = "./server.ts"
assets = { directory = "./build/client" }

# KV Namespaces
kv_namespaces = [
  { binding = "AUTH_STORE", id = "9840b920604d4fee80f95e19b4003e1a", preview_id = "29d0f941e9ea4e44ae495207b7e56a48" }
]

# Compatibility Flags

compatibility_flags = ["nodejs_compat"]

[vars]
SESSION_SECRET = "your-session-secret"

# Workers Logs
[observability]
enabled = true


